project:
  type: book
  output-dir: docs

book:
  title: "Quantitative Analysis of (Messy) Field Data"
  subtitle: "University of Wyoming -- ZOO-5500 (CRN 13415) | ECOL-5500 (CRN 13417)"
  sidebar:
    logo: graphics/jackalope_graphics/analytical_jackalope.png
  chapters:
    - part: "Course Overview"
      chapters:   
        - index.qmd
        - chapters/02_course_intro.qmd
        - chapters/04_syllabus.qmd
        - chapters/calendar_sp26.qmd
        - chapters/05_ai.qmd  
        - chapters/06_preparing_yourself.qmd
        - chapters/assignment_grades.qmd
    # --- MAIN BODY ---
    - part: "Part I: Chaos to Columns"
      # chapters:
        # - chapters/statistical_aphorisms.qmd
        # - chapters/naming_conventions.qmd
        # - chapters/data_exploration.qmd
        # - chapters/preprocessing.qmd
    - part: "Part II: Columns to Curves"
      # chapters: 
        # - chapters/intro_modeling.qmd
        # - chapters/glm_poisson.qmd
    - part: "Part III: Curves to Meaning"


format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    number-sections: true
    number-depth: 3
    css: styles.css

editor: source
