project:
  type: book
  output-dir: docs

book:
  title: "Quantitative Analysis of (Messy) Field Data"
  subtitle: "University of Wyoming -- ZOO-5500 (CRN 13415) | ECOL-5500 (CRN 13417)"
  sidebar:
    logo: graphics/jackalope_graphics/analytical_jackalope.png
    collapse-level: 1
  chapters:
    - part: "Course Overview"
      chapters:   
        - index.qmd
        - chapters/course_intro.qmd
        - chapters/syllabus.qmd
        - chapters/calendar_sp26.qmd
        - chapters/ai_policy.qmd  
        - chapters/preparing_yourself.qmd
        - chapters/assignment_grades.qmd
        - chapters/project_scoping.qmd
    # --- MAIN BODY ---
    - part: "Part âˆ…: AI preparation"
      chapters:   
        - chapters/ai_prompting.qmd
        - chapters/using_jackalope_gpt.qmd
    - part: "Part I: Reproducible Analyses"
      chapters: 
        - chapters/reproducible_workflow_intro.qmd
        - chapters/nature_of_data.qmd
        - chapters/metadata_low_friction.qmd
        - chapters/naming_conventions.qmd
    - part: "Part II: Chaos to Columns"
      chapters:
        - chapters/data_exploration_intro.qmd
        - chapters/data_exploration_toolkit.qmd
        - chapters/outliers.qmd
        - chapters/tutorial_data_exploration.qmd
    - part: "Part III: Columns to Curves"
      chapters: 
        - chapters/statistical_aphorisms.qmd
        - chapters/intro_modeling.qmd
        - chapters/intro_glms.qmd
        - chapters/tutorial_glms.qmd
        - chapters/glm_partial_association.qmd
        - chapters/DHARMA_diagnostics.qmd
        # - chapters/aic_information_theory.qmd
    - part: "Part IV: Curves to Meaning"


format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    number-sections: true
    number-depth: 3
    css: styles.css
    code-copy: true
    
website:
  favicon: graphics/favicon/favicon.ico

editor: source
